[package]
name = "yggdrasil-address"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "IPv6 address derivation for the Yggdrasil network"

[dependencies]
yggdrasil-types.workspace = true
